cat /etc/default/locale
```
#  File generated by update-locale
LANG="en_US.UTF-8"

```
update-locale LANG="en_US.UTF-8"
locale -a

locale
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

 nano /etc/locale.gen
 取消注释
 然后重新运行
 locale-gen

 sudo sed -i 's/^# *zh_CN.UTF-8 UTF-8/zh_CN.UTF-8 UTF-8/' /etc/locale.gen
sudo locale-gen
locale-gen zh_CN.UTF-8

 也可以
 dpkg-reconfigure locales

 nginx 配置的长度是80
